### ISSUE TITLE
TypeError: plugin is not a function

### ISSUE THREAD

**Issue by curran** [dmapper/sharedb-access#4]
Hello, 
I'm attempting to start using sharedb-access. I tried to follow the setup steps from the README, and I'm getting the following error:

```
/Users/curran/repos/myApp/node_modules/racer/lib/util.js:178
    plugin(this, options);
    ^

TypeError: plugin is not a function
    at Racer.use (/Users/curran/repos/myApp/node_modules/racer/lib/util.js:178:5)
    at new ShareDBAccess (/Users/curran/repos/myApp/node_modules/sharedb-access/lib/index.js:29:11)
    at ShareDBAccess (/Users/curran/repos/myApp/node_modules/sharedb-access/lib/index.js:22:48)
    at Racer.use (/Users/curran/repos/myApp/node_modules/racer/lib/util.js:178:5)
    at store (/Users/curran/repos/myApp/server/store.js:10:9)
    at /Users/curran/repos/myApp/server.js:17:40
    at Racer.Derby.run (/Users/curran/repos/myApp/node_modules/derby/lib/Derby.server.js:17:5)
    at Object.<anonymous> (/Users/curran/repos/myApp/server.js:8:7)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
```

Here we can see the source of the error within sharedb-access:

https://github.com/dmapper/sharedb-access/blob/master/lib/index.js#L29

``` js
backend.use('doc', this.docHandler.bind(this));
```

The definition of `use` can be found here in racer:

https://github.com/derbyjs/racer/blob/master/lib/util.js#L173

``` js
function use(plugin, options) {
  // Don't include a plugin more than once
  var plugins = this._plugins || (this._plugins = []);
  if (plugins.indexOf(plugin) === -1) {
    plugins.push(plugin);
    plugin(this, options);
  }
  return this;
}
```

It seems the `use` function does not take a string as the first argument. This can be traced to a change by @nateps in 2014

https://github.com/derbyjs/racer/commit/4317c8b72b066bcda7c44afae8d4a0b34afb50f0#diff-3deb3f32958bb937ae05c6f3e4abbdf5L170

I'm not sure if this is actually the cause of the error though, because sharedb-access was updated more recently than that by @cjblomqvist

https://github.com/dmapper/sharedb-access/commit/9aa2d9edbe4b9db2a23ed0c125bd266ea8c1bfa2

Here are the versions from my package.json:

```
  "dependencies": {
    "async": "^2.0.0-rc.5",
    "bcryptjs": "^2.3.0",
    "body-parser": "^1.15.1",
    "compression": "^1.6.2",
    "connect-mongo": "^1.2.0",
    "cookie-parser": "^1.4.3",
    "derby": "^0.8.5",
    "derby-debug": "^0.1.0",
    "derby-login": "^1.1.1",
    "express": "^4.13.4",
    "express-session": "^1.13.0",
    "racer-bundle": "^0.2.4",
    "racer-highway": "^7.0.2",
    "redis-url": "^1.2.1",
    "serve-favicon": "^2.3.0",
    "serve-static": "^1.10.3",
    "sharedb-access": "^3.0.0",
    "sharedb-mongo": "^0.8.7",
    "sharedb-redis-pubsub": "^0.3.1"
```

Here's where I'm adding sharedb-access (inside [store.js from generator-derby](https://github.com/derbyparty/generator-derby/blob/master/app/templates/server/_store.js)):

``` js
var shareDbMongo = require("sharedb-mongo");
var shareDbAccess = require("sharedb-access");

module.exports = store;

function store(derby, publicDir) {
  var db = shareDbMongo(process.env.MONGO_URL + "?auto_reconnect=true", {safe: true});

  derby.use(require("racer-bundle"));
  derby.use(shareDbAccess);

  var redis = require("redis-url");
  var redisPubSub = require("sharedb-redis-pubsub");
```

Any ideas why this error is occurring or how it can be fixed? Thank you.

**Comment by minicuper** [comment]
For now it's impossible to bootstrap sharedb-access with derby.use. Shortly because @nateps removed the line from racer while refactoring - https://github.com/derbyjs/racer/commit/726b29a7fea2a405eaa51d17b6ffdf5be59b2e79#diff-289eef5bb68f58795bf5ba334c5f736dL9

I hope he will accept my PR to fix this - https://github.com/derbyjs/racer/pull/246

For now the only way to pickup sharedb-access is something like this:

```
backend = derby.createBackend(...)
require('sharedb-access') backend
```

**Comment by curran** [comment]
After a bit more research, I realized that the wrong `use` is getting invoked. If the text of `use` is printed like this:

``` js
function ShareDBAccess(backend, options){
  if (!(this instanceof ShareDBAccess)) return new ShareDBAccess(backend, options);

  this.options = options || {};

  this.allow = {};
  this.deny = {};

  console.log(backend.use.toString());

  backend.use('doc', this.docHandler.bind(this));
  backend.use('apply', this.applyHandler.bind(this));
  backend.use('commit', this.commitHandler.bind(this));

  this.initBackend(backend);
}
```

The following gets printed:

``` js
function use(plugin, options) {
  // Don't include a plugin more than once
  var plugins = this._plugins || (this._plugins = []);
  if (plugins.indexOf(plugin) === -1) {
    plugins.push(plugin);
    plugin(this, options);
  }
  return this;
}
```

This is the [`use` function from Racer](https://github.com/derbyjs/racer/blob/master/lib/util.js#L173), but really what it _should_ be is the [`use` function from ShareDB Backend](https://github.com/share/sharedb/blob/master/lib/backend.js#L112).

Any ideas how to change this so the correct `use` function gets used?

Also, does it perhaps depend on whether or not `derby.use(require("sharedb-access"));` is invoked before or after setting up the store?

**Comment by curran** [comment]
I think I found the solution, to invoke sharedb-access like this after the store gets created:

``` js
require("sharedb-access")(store);
```

**Comment by curran** [comment]
Thank you @zag2art for your reply. This approach is working for me.
